version: '3.5'
services:
  api:
    image: ${IMAGE_NAME}
    container_name: test-nodejs-webbylab
    restart: unless-stopped
    env_file: .env
    environment:
      PORT: ${PORT}
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - 8001:${PORT}
